services:
  mongodb:
    image: mongo:5.0
    container_name: attendance-mongodb
    restart: unless-stopped
#    ports:
#      - "25756:27017"
    volumes:
    - mongodb_data:/data/db
    - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: attendance_db

  server:
    build:
      context: ./server  
      dockerfile: Dockerfile 
    container_name: attendance-server
    restart: unless-stopped
    ports:
      - "8010:8010"
    environment:
      PORT: 8010
      MONGODB_URI: mongodb://mongodb:27017
      DB_NAME: attendance_db
      JWT_SECRET: blah&blah$super@secure&hash
    depends_on:
      - mongodb

  client:
    build:
      context: ./client  
      dockerfile: Dockerfile 
      args:
        - VITE_API_BASE_URL=https://submission.souravcodes.in/alpha/api
       #- VITE_API_BASE_URL=http://localhost:8010/api
    container_name: attendance-client
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      VITE_API_URL: https://submission.souravcodes.in/alpha/api
    depends_on:
      - server

volumes:
  mongodb_data:
